### ISSUE TITLE
Bug reported: individual nanotubes in MWNT have different lengths

### ISSUE THREAD

**Issue by hoang6** [scikit-nano/scikit-nano#9]
Hi Andrew,

When I generated MWNT, the individual tubes don't have the same length Lz, so they aren't periodic in the z-direction. Please take a look at the photo attached. Can you please tell me what may be the problem here?

Thanks,

Tom

![screen shot 2017-01-06 at 10 25 24 am](https://cloud.githubusercontent.com/assets/2857972/21724708/1e47496c-d3fb-11e6-9d68-f681787a173c.png)

**Comment by the-real-droop** [comment]
Hi Tom,

It looks like you're trying to generate a MWNT using incommensurate chiralities. If you want all the walls to be periodic along Lz, the chiralities need to be commensurate, meaning all armchair or zigzag. There might be special cases for different chirality walls which also satisfy periodicity, but I don't know off the top of my head.

Let me know if you're still running into bugs and I can dig into it further. This project has been on the backburner for awhile but I hope to start development again soon.

Cheers,
Andrew

**Comment by hoang6** [comment]
Hi Andrew,

Thanks so much for your help! My bad, I should have paid more attention to the chirality property!

Best,

Tom
